FROM alpine:latest

FROM node:latest

RUN npm install -g serve

# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app
 
# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./
 
# Installs all node packages
RUN npm install
 
# Copies everything over to Docker environment
COPY . .

ENV NODE_ENV=production
RUN npm run build
CMD serve -p $PORT -s build